name: Deploy Supabase Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g supabase

      - name: Deploy send-web-reminder
        run: supabase functions deploy send-web-reminder --project-ref ${{ secrets.PROJECT_URL }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SERVICE_ROLE}}

      - name: Deploy check-reminders
        run: supabase functions deploy check-reminders --project-ref ${{ secrets.PROJECT_URL }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SERVICE_ROLE}}
